const bcrypt = require('bcryptjs')
const data = {
  users: [
    {
      name: 'Whimzy',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Whimzy',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 0,
        numReviews: 0,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
     
      name: 'Multicolor Woolen Hat',
      category: 'Hats',
      image: '/images/img1.jpg',
      price: 11.99,
      countInStock: 50,
      brand: 'Cap',
      rating: 0,
      numReviews: 0,
      description: 'High Quality Product',
    },
    {
      
      name: 'Kids Woolen Sliding',
      category: 'Shoes',
      image: '/images/img2.jpg',
      price: 12.99,
      countInStock: 20,
      brand: 'Shoes',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Woolen Penguin Hat',
      category: 'Hats',
      image: '/images/img3.jpg',
      price: 11.99,
      countInStock: 50,
      brand: 'Cap',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Orange Woolen Hat',
      category: 'Hats',
      image: '/images/img4.jpg',
      price: 11.99,
      countInStock: 50,
      brand: 'Cap',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Red, White & Blue Woolen Hat',
      category: 'Hats',
      image: '/images/img5.jpg',
      price: 11.99,
      countInStock: 40,
      brand: 'Cap',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      
      name: 'Muga Necklace',
      category: 'Necklaces',
      image: '/images/img6.jpg',
      price: 12.99,
      countInStock: 6,
      brand: 'Necklece',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      
      name: 'Woolen Headband',
      category: 'Hats',
      image: '/images/img7.jpg',
      price: 11.99,
      countInStock: 50,
      brand: 'Cap',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Sirupate Khukuri - Yellow',
      category: 'Knives',
      image: '/images/img8.jpg',
      price: 45.99,
      countInStock: 10,
      brand: 'Knife',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Silver & Gold Plated Chain',
      category: 'Necklaces',
      image: '/images/img9.jpg',
      price: 13.99,
      countInStock: 3,
      brand: 'Necklece',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Grey & Pink Woolen Hat',
      category: 'Hats',
      image: '/images/img10.jpg',
      price: 11.99,
      countInStock: 50,
      brand: 'Cap',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
   
    {
    
      name: 'Bead and Stone Chain',
      category: 'Necklaces',
      image: '/images/img12.jpg',
      price: 12.99,
      countInStock: 4,
      brand: 'Necklece',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
    
      name: 'Kids Felt High Top Shoes - Purple',
      category: 'Shoes',
      image: '/images/img13.jpg',
      price: 25.99,
      countInStock: 20,
      brand: 'Shoes',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      
      name: 'Felt Indoor Carpet - Purple',
      category: 'Rugs',
      image: '/images/img14.jpg',
      price: 219.99,
      countInStock: 13,
      brand: 'Mat',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Girls Felt Sliding',
      category: 'Shoes',
      image: '/images/img15.jpg',
      price: 12.99,
      countInStock: 20,
      brand: 'Shoes',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      
      name: 'Gold Plated Chain With Stones',
      category: 'Necklaces',
      image: '/images/img16.jpg',
      price: 25.99,
      countInStock: 6,
      brand: 'Necklece',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Kids Felt High Top Shoes - Blue',
      category: 'Shoes',
      image: '/images/img17.jpg',
      price: 25.99,
      countInStock: 20,
      brand: 'Shoes',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
    
      name: 'Flower Purse',
      category: 'Bags',
      image: '/images/img18.jpg',
      price: 15.99,
      countInStock: 23,
      brand: 'Bag',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Gold Buddha Statue',
      category: 'Statues',
      image: '/images/img20.jpg',
      price: 506.99,
      countInStock: 4,
      brand: 'Idol',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      
      name: 'Purse Om',
      category: 'Bags',
      image: '/images/img21.jpg',
      price: 115.99,
      countInStock: 19,
      brand: 'Bag',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Kids Felt Shoe',
      category: 'Shoes',
      image: '/images/img22.jpg',
      price: 12.99,
      countInStock: 10,
      brand: 'Shoes',
      rating: 0,
      numReviews: 0,
      description: 'For kids ages 2-6',
    },
    {
    
      name: 'Gold Plated Chain With Muga Stone',
      category: 'Necklaces',
      image: '/images/img24.jpg',
      price: 7.99,
      countInStock: 5,
      brand: 'Necklece',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },

    {
    
      name: 'Kids Felt Sliding',
      category: 'Shoes',
      image: '/images/img26.jpg',
      price: 12.99,
      countInStock: 10,
      brand: 'Shoes',
      rating: 0,
      numReviews: 0,
      description: 'For kids ages 2-6',
    },
    {
     
      name: 'Gold Singing Bowl',
      category: 'Singing Bowls',
      image: '/images/img27.jpg',
      price: 29.99,
      countInStock: 20,
      brand: 'Bowl',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
    
      name: 'Sirupate Khukuri - Blue',
      category: 'Knives',
      image: '/images/img28.jpg',
      price: 45.99,
      countInStock: 10,
      brand: 'Knife',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Sirupate Khukuri - Red',
      category: 'Knives',
      image: '/images/img29.jpg',
      price: 45.99,
      countInStock: 10,
      brand: 'Knife',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Sherpa Purse',
      category: 'Bags',
      image: '/images/img30.jpg',
      price: 15.99,
      countInStock: 27,
      brand: 'Bag',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Felt Indoor Carpet - Blue',
      category: 'Rugs',
      image: '/images/img31.jpg',
      price: 219.99,
      countInStock: 25,
      brand: 'Mat',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Buddha Statue',
      category: 'Statues',
      image: '/images/img33.jpg',
      price: 506.99,
      countInStock: 6,
      brand: 'Idol',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
    {
     
      name: 'Stone Ring',
      category: 'Rings',
      image: '/images/img32.jpg',
      price: 12.99,
      countInStock: 11,
      brand: 'Ring',
      rating: 0,
      numReviews: 0,
      description: 'high quality product',
    },
   
  ],
};
// export default data;
module.exports = data;
